load ././project_cassette//aligned_structures/4xxo_A.pdb 
load ././project_cassette//aligned_structures/4xxo_B.pdb 
load ././project_cassette//aligned_structures/2m65_A.pdb 
load ././project_cassette//aligned_structures/5sww_AE.pdb 
load ././project_cassette//aligned_structures/5sww_BF.pdb 
load ././project_cassette//aligned_structures/5sww_CG.pdb 
load ././project_cassette//aligned_structures/5sww_DH.pdb 
load ././project_cassette//aligned_structures/5td5_AC.pdb 
load ././project_cassette//aligned_structures/5cqd_A.pdb 
load ././project_cassette//aligned_structures/5cqh_A.pdb 
load ././project_cassette//aligned_structures/5cqi_A.pdb 
load ././project_cassette//aligned_structures/5cqk_A.pdb 
load ././project_cassette//aligned_structures/5cqd_C.pdb 
load ././project_cassette//aligned_structures/hom_a3b_ctd_shiv.pdb 
load ././project_cassette//aligned_structures/2nbq_A.pdb 
load ././project_cassette//aligned_structures/2jyw_A.pdb 
load ././project_cassette//aligned_structures/3e1u_A.pdb 
load ././project_cassette//aligned_structures/2kbo_A.pdb 
load ././project_cassette//aligned_structures/2kem_A.pdb 
load ././project_cassette//aligned_structures/3iqs_A.pdb 
load ././project_cassette//aligned_structures/3ir2_A.pdb 
load ././project_cassette//aligned_structures/3ir2_B.pdb 
load ././project_cassette//aligned_structures/3v4k_A.pdb 
load ././project_cassette//aligned_structures/3v4k_B.pdb 
load ././project_cassette//aligned_structures/3v4j_A.pdb 
load ././project_cassette//aligned_structures/3v4j_B.pdb 
load ././project_cassette//aligned_structures/4rov_A.pdb 
load ././project_cassette//aligned_structures/4rov_B.pdb 
load ././project_cassette//aligned_structures/4row_A.pdb 
load ././project_cassette//aligned_structures/hom_a3b_ntd_shiv.pdb 
load ././project_cassette//aligned_structures/3vm8_A.pdb 
load ././project_cassette//aligned_structures/3vm8_B.pdb 
load ././project_cassette//aligned_structures/3vow_A.pdb 
load ././project_cassette//aligned_structures/3vow_B.pdb 
load ././project_cassette//aligned_structures/hom_a3d_ntd_shiv.pdb 
load ././project_cassette//aligned_structures/hom_a3d_ctd_shiv.pdb 
load ././project_cassette//aligned_structures/hom_a3f_ntd_shiv.pdb 
load ././project_cassette//aligned_structures/3wus_A.pdb 
load ././project_cassette//aligned_structures/3wus_B.pdb 
load ././project_cassette//aligned_structures/4j4j_A.pdb 
load ././project_cassette//aligned_structures/4j4j_B.pdb 
load ././project_cassette//aligned_structures/4iou_A.pdb 
load ././project_cassette//aligned_structures/4iou_B.pdb 
load ././project_cassette//aligned_structures/4iou_C.pdb 
load ././project_cassette//aligned_structures/4iou_D.pdb 
load ././project_cassette//aligned_structures/5hx4_A.pdb 
load ././project_cassette//aligned_structures/5hx4_B.pdb 
load ././project_cassette//aligned_structures/5hx5_A.pdb 
load ././project_cassette//aligned_structures/5hx5_B.pdb 
load ././project_cassette//aligned_structures/2mzz_A.pdb 
load ././project_cassette//aligned_structures/hom_a3g_ntd_shiv.pdb 
load ././project_cassette//aligned_structures/5k81_A.pdb 
load ././project_cassette//aligned_structures/5k81_B.pdb 
load ././project_cassette//aligned_structures/5k81_C.pdb 
load ././project_cassette//aligned_structures/5k81_D.pdb 
load ././project_cassette//aligned_structures/5k81_E.pdb 
load ././project_cassette//aligned_structures/5k81_F.pdb 
load ././project_cassette//aligned_structures/5k82_A.pdb 
load ././project_cassette//aligned_structures/5k82_B.pdb 
load ././project_cassette//aligned_structures/5k82_C.pdb 
load ././project_cassette//aligned_structures/5k82_D.pdb 
load ././project_cassette//aligned_structures/5k83_AH.pdb 
load ././project_cassette//aligned_structures/5k83_B.pdb 
load ././project_cassette//aligned_structures/5k83_CI.pdb 
load ././project_cassette//aligned_structures/5k83_D.pdb 
load ././project_cassette//aligned_structures/5k83_EJ.pdb 
load ././project_cassette//aligned_structures/5k83_F.pdb 
load ././project_cassette//aligned_structures/hom_a3h_shiv.pdb 
load ././project_cassette//aligned_structures/5jj4_A.pdb 
load ././project_cassette//aligned_structures/5jj4_B.pdb 
load ././project_cassette//aligned_structures/5jj4_C.pdb 
load ././project_cassette//aligned_structures/2nyt_A.pdb 
load ././project_cassette//aligned_structures/2nyt_B.pdb 
load ././project_cassette//aligned_structures/2nyt_C.pdb 
load ././project_cassette//aligned_structures/2nyt_D.pdb 
cmd.show("cartoon"   ,"all")
cmd.hide("lines"     ,"all")
set orthoscopic, on 
